cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    token:
      secret-key: a1b2c3d4f5
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.99:3306/api-gateway?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
spring-doc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true